name: Build and Deploy to OSS

on:
  push:
    branches:
      - main  # 监控主分支

jobs:
  build-and-oss:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.19.1' 

    # - name: Install dependencies
    #   run: npm install
    # - name: install global package
    #   run: npm install yarn lerna -g

    # - name: Build project
    #   run: lerna run build

    # - name: Upload to OSS
    #   run: |
    #      curl https://gosspublic.alicdn.com/ossutil/install.sh | sudo bash
    # - name: oss config
    #   run: |
    #     echo "${{ secrets.OSS_ACCESS_KEY_ID }}"
    #     echo ${{ secrets.OSS_ACCESS_KEY_SECRET }}
    #     touch .ossutilconfig
    #     echo "[Credentials]" > .ossutilconfig
    #     echo "language=CH" >> .ossutilconfig
    #     echo "accessKeyID=${{ secrets.OSS_ACCESS_KEY_ID }}" >> .ossutilconfig
    #     echo "accessKeySecret=${{ secrets.OSS_ACCESS_KEY_SECRET }}" >> .ossutilconfig
    #     echo "endpoint=https://oss-cn-hangzhou.aliyuncs.com" >> .ossutilconfig
    - name: upload oss
      run:  |
     
        for app in ./packages/*; do
          if [ -d "$app/dist" ]; then
            echo "Uploading files from $app/dist to OSS..."
            ossutil cp -r ./packages/$app/dist oss://bressanone-bucket2/micros/$app
          else 
            echo "$app/dist not exist"
          fi
        done
      # run: |
      #   npm install -g aliyun-cli
      #   aliyun oss cp -r ./build oss://$OSS_BUCKET/ --region $OSS_REGIONGIT

      # ossutil cp -r ./packages/micro-app2/dist oss://bressanone-bucket2/micros/



for app in ./packages/; do
  if [ -d "$app/dist2" ]; then
    echo "Uploading files from $app/dist to OSS..."
    ossutil cp -r ./packages/$app/dist oss://bressanone-bucket2/micros/$app
  else 
    echo "$app/dist not exist"
  fi
done