name: Build and Deploy to OSS

on:
  push:
    branches:
      - main  # 监控主分支

jobs:
  build-and-oss:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.19.1' 

    # - name: Install dependencies
    #   run: npm install
    # - name: install global package
    #   run: npm install yarn lerna -g

    # - name: Build project
    #   run: lerna run build

    - name: Upload to OSS
      # env:
      #   OSS_REGION: <your-oss-region>  # 比如 oss-cn-hangzhou
      #   OSS_BUCKET: <your-bucket-name>
      #   OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
      #   OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
      run: |
         curl https://gosspublic.alicdn.com/ossutil/install.sh | sudo bash
    - name: oss config
      run: |
        ls -a 
        # cat <<EOL > /home/user/.ossutilconfig \
        # [Credentials] \
        # language=CH \
        # accessKeyID=$OSS_ACCESS_KEY_ID \
        # accessKeySecret=$OSS_ACCESS_KEY_SECRET \
        # endpoint=https://oss-cn-hangzhou.aliyuncs.com \
        # EOL
    #     cat /home/user/.ossutilconfig
    # - name: upload oss
    #   run:  ossutil
      # run: |
      #   npm install -g aliyun-cli
      #   aliyun oss cp -r ./build oss://$OSS_BUCKET/ --region $OSS_REGION